services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-testdb}
      - MYSQL_USER=${MYSQL_USER:-testuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-testpwd}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
      - .env
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    depends_on:
      - redis
      - mysql

volumes:
  redis-data:
  mysql-data: 