services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lowcodeapi}
      - MYSQL_USER=${MYSQL_USER:-lowcodeapi}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-lowcodeapi}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  mysql-data: 